/*
 * WinchMotor.h
 *
 *  Created on: 30.03.2018
 *      Author: mario
 */

#ifndef SOURCES_PROJECT_HEADERS_WINCHMOTOR_H_
#define SOURCES_PROJECT_HEADERS_WINCHMOTOR_H_

enum DirectionWinch {
	FORWARDWINCH,
	BACKWARDWINCH,
	STOPPEDWINCH
};

enum ModuloValueWinch {
	FIFTH1WINCH,
	FIFTH2WINCH,
	FIFTH3WINCH,
	FIFTH4WINCH,
	FIFTH5WINCH
};

enum StatusWinch {
	RESETWINCH,
	DRIVEWINCH,
	STOPANDWAITWINCH
};

#endif /* SOURCES_PROJECT_HEADERS_WINCHMOTOR_H_ */
